export const baseUrl = 'https://zeta-hackathon.herokuapp.com/'

export const base = 'http://e1c1-117-242-232-51.ngrok.io'

// Object {
//     "config": Object {
//       "adapter": [Function xhrAdapter],
//       "data": "username=879uu&password=Man",
//       "headers": Object {
//         "Accept": "application/json, text/plain, */*",
//         "Content-Type": "application/x-www-form-urlencoded",
//       },
//       "maxBodyLength": -1,
//       "maxContentLength": -1,
//       "method": "post",
//       "timeout": 0,
//       "transformRequest": Array [
//         [Function transformRequest],
//       ],
//       "transformResponse": Array [
//         [Function transformResponse],
//       ],
//       "url": "https://bed6-117-242-232-51.ngrok.io/login",
//       "validateStatus": [Function validateStatus],
//       "xsrfCookieName": "XSRF-TOKEN",
//       "xsrfHeaderName": "X-XSRF-TOKEN",
//     },
//     "data": "",
//     "headers": Object {
//       "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
//       "content-length": "0",
//       "date": "Thu, 26 Aug 2021 15:53:04 GMT",
//       "expires": "0",
//       "pragma": "no-cache",
//       "set-cookie": Array [
//         "JSESSIONID=34EAD5AE5AD4F86B03B6101D985736DE; Path=/; HttpOnly",
//       ],
//       "x-content-type-options": "nosniff",
//       "x-frame-options": "DENY",
//       "x-xss-protection": "1; mode=block",
//     },
//     "request": XMLHttpRequest {
//       "DONE": 4,
//       "HEADERS_RECEIVED": 2,
//       "LOADING": 3,
//       "OPENED": 1,
//       "UNSENT": 0,
//       "_aborted": false,
//       "_cachedResponse": undefined,
//       "_hasError": false,
//       "_headers": Object {
//         "accept": "application/json, text/plain, */*",
//         "content-type": "application/x-www-form-urlencoded",
//       },
//       "_incrementalEvents": false,
//       "_lowerCaseResponseHeaders": Object {
//         "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
//         "content-length": "0",
//         "date": "Thu, 26 Aug 2021 15:53:04 GMT",
//         "expires": "0",
//         "pragma": "no-cache",
//         "set-cookie": "JSESSIONID=34EAD5AE5AD4F86B03B6101D985736DE; Path=/; HttpOnly",
//         "x-content-type-options": "nosniff",
//         "x-frame-options": "DENY",
//         "x-xss-protection": "1; mode=block",
//       },
//       "_method": "POST",
//       "_perfKey": "network_XMLHttpRequest_https://bed6-117-242-232-51.ngrok.io/login",
//       "_requestId": null,
//       "_response": "",
//       "_responseType": "",
//       "_sent": true,
//       "_subscriptions": Array [],
//       "_timedOut": false,
//       "_trackingName": "unknown",
//       "_url": "https://bed6-117-242-232-51.ngrok.io/login",
//       "readyState": 4,
//       "responseHeaders": Object {
//         "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
//         "content-length": "0",
//         "date": "Thu, 26 Aug 2021 15:53:04 GMT",
//         "expires": "0",
//         "pragma": "no-cache",
//         "set-cookie": "JSESSIONID=34EAD5AE5AD4F86B03B6101D985736DE; Path=/; HttpOnly",
//         "x-content-type-options": "nosniff",
//         "x-frame-options": "DENY",
//         "x-xss-protection": "1; mode=block",
//       },
//       "responseURL": "https://bed6-117-242-232-51.ngrok.io/login",
//       "status": 200,
//       "timeout": 0,
//       "upload": XMLHttpRequestEventTarget {},
//       "withCredentials": true,
//     },
//     "status": 200,
//     "statusText": undefined,
//   }